update dbo.listaio set nome = 'Contra-vale' where nome = 'Comprovante de contra-vale'
update dbo.listaio set nome = 'Repique' where nome = 'Comprovante de repique'
update dbo.listaio set nome = 'Itens cancelados' where nome = 'Impressão dos itens cancelados'
update dbo.listaio set nome = 'Itens transferidos' where nome = 'Impressão dos itens transferidos'
update dbo.listaio set nome = 'Recibo de pagamento' where nome = 'Impressão de recibo de pagamento'
update dbo.listaio set nome = 'Recibo de pagamento parcial' where nome = 'Impressão do recibo de pagamento parcial'
update dbo.listaio set nome = 'Conferência de conta (mesa)' where nome = 'Impressão da conferência de conta'
update dbo.listaio set nome = 'Conferência de conta (ficha)' where nome = 'Impressão de parciais'
update dbo.listaio set nome = 'Sangria' where nome = 'Comprovante de sangria'
update dbo.listaio set nome = 'Suprimento' where nome = 'Comprovante de suprimento'
update dbo.listaio set nome = 'Estorno' where nome = 'Comprovante de estorno'
update dbo.listaio set nome = 'Estorno fiscal eletrônico' where nome = 'Comprovante de estorno de NFCe'
update dbo.listaio set nome = 'Crédito em conta assinada' where nome = 'Comprovante de crédito em conta assinada'
update dbo.listaio set nome = 'Débito em conta assinada' where nome = 'Comprovante de débito em conta assinada'