if (object_id('tempdb..##bandeira') is not null)
  drop table ##bandeira

create table ##bandeira(
    id int not null,
    nome varchar(50) not null,
    tipo varchar(25) not null,
    aliases varchar(150) null
)

insert into ##bandeira ( id, nome, tipo, aliases )
values
( 0,  'Desconhecido', '', null),
( 1,  'Visa', 'credito', 'Crédito;VISA Crediário;VISA Crédito;VISA Parcelado Loja'),
( 2,  'Mastercard', 'credito', 'AVISTA;MAIS;REDE ESTRADA'),
( 3,  'Diners', 'credito', null),
( 4,  'Amex', 'credito', null),
( 5,  'Sollo', 'credito', null),
( 6,  'Sidecard', 'credito', null),
( 7,  'Private Label', 'credito', null),
( 8,  'Redeshop', 'credito', null),
( 9,  'Pão de Açucar', 'credito', null),
( 10, 'Fininvest', 'credito', null),
( 11, 'JCB', 'credito', null),
( 12, 'Hipercard', 'credito', null),
( 13, 'Aura', 'credito', null),
( 14, 'Losango', 'credito', null),
( 15, 'Sorocred', 'credito', null),
( 30, 'Cabal', 'credito', null),
( 31, 'Elo', 'credito', 'ELO Crédito'),
( 33, 'Policard', 'credito', 'FROTA;PAT'),
( 35, 'Banescard', 'credito', 'BANESCARD crédito à vista;BANESE CARD;Crédito com senha'),
( 38, 'Cetelem', 'credito', null),
( 41, 'Sicredi', 'credito', null),
( 43, 'Coopercred', 'credito', null),
( 45, 'A Vista', 'credito', null),
( 57, 'Credisystem', 'credito', null),
( 58, 'Banpará', 'credito', null),
( 60, 'Amazoncard', 'credito', null),
( 61, 'Yamada', 'credito', null),
( 62, 'Goiascard', 'credito', null),
( 63, 'Credpar', 'credito', null),
( 64, 'Boticario', 'credito', null),
( 65, 'Ascard', 'credito', null),
( 66, 'Jetpar', 'credito', null),
( 67, 'Maxxcard', 'credito', null),
( 68, 'Garantido', 'credito', null),
( 69, 'Amazon Prime', 'credito', null),
( 70, 'CredZ', 'credito', 'CredZ crédito à vista'),
( 71, 'Credishop', 'credito', 'CREDI-SHOP'),
( 10001,  'Ticket', 'voucher', null),
( 10002,  'Visa Vale', 'voucher', null),
( 10003,  'Sodexo', 'voucher', null),
( 10004,  'Nutricash', 'voucher', null),
( 10005,  'Greencard', 'voucher', 'GREEN CARD'),
( 10006,  'Planvale', 'voucher', null),
( 10007,  'Banquet', 'voucher', null),
( 10008,  'Verocheque', 'voucher', 'VALECARD;VEROCARD'),
( 10009,  'Sapore', 'voucher', null),
( 10010,  'BNB Clube', 'voucher', 'BNBCLUBE'),
( 10011,  'Valecard', 'voucher', 'VALEMULTI'),
( 10012,  'Cabal', 'voucher', null),
( 10013,  'Elo', 'voucher', null),
( 10014,  'Discovery', 'voucher', null),
( 10015,  'Goodcard', 'voucher', 'GOOD CARD'),
( 10016,  'Policard', 'voucher', 'FROTA;PAT'),
( 10017,  'Cardsystem', 'voucher', null),
( 10018,  'Bonus CBA', 'voucher', null),
( 10019,  'Alelo', 'voucher', null),
( 10020,  'Banescard', 'voucher', 'BANESE CARD'),
( 10021,  'Alelo Refeição', 'voucher', null),
( 10022,  'Alelo Alimentação', 'voucher', null),
( 10023,  'Alelo Cultura', 'voucher', null),
( 10024,  'Ticket Refeição', 'voucher', 'Alimentação;Refeição;TICKET'),
( 10025,  'Ticket Alimentação', 'voucher', null),
( 10026,  'Ticket Parceiro', 'voucher', null),
( 10027,  'Ticket Cultura', 'voucher', null),
( 10028,  'Sodexo Refeição', 'voucher', 'SODEXO'),
( 10029,  'Sodexo Alimentação', 'voucher', null),
( 10030,  'Sodexo Gift', 'gift', null),
( 10031,  'Sodexo Premium', 'voucher', null),
( 10032,  'Sodexo Cultura', 'voucher', null),
( 10033,  'Sodexo Combustível', 'voucher', null),
( 10037,  'Sorocred', 'voucher', null),
( 10039,  'Valemulti', 'voucher', null),
( 10040,  'Valefrota Combustível', 'voucher', null),
( 10044,  'Coopercred', 'voucher', null),
( 10046,  'Valefácil', 'voucher', null),
( 10047,  'VR Refeição', 'voucher', null),
( 10048,  'VR Alimentação', 'voucher', null),
( 10049,  'VR Combustível', 'voucher', null),
( 10050,  'VR Cultura', 'voucher', null),
( 10051,  'Planvale Cultura', 'voucher', null),
( 10052,  'Banrisul Cultura', 'voucher', null),
( 10053,  'Nutricash Cultura', 'voucher', null),
( 10054,  'Ticket Combustível', 'voucher', 'TICKET CAR'),
( 10055,  'Valecard Cultura', 'voucher', null),
( 10070,  'VR Benefício', 'voucher', null),
( 10071,  'Planvale Benefício', 'voucher', null),
( 10072,  'Planvale Alimentação', 'voucher', null),
( 10073,  'Planvale Refeição', 'voucher', null),
( 10074,  'Planvale Combustível', 'voucher', null),
( 10075,  'Planvale Farmácia', 'voucher', null),
( 20001,  'Maestro', 'debito', null),
( 20002,  'Visa Electron', 'debito', null),
( 20003,  'Cabal', 'debito', null),
( 20012,  'Cabal', 'debito', null),
( 20013,  'Elo', 'debito', 'ELO Débito'),
( 20032,  'Elo', 'debito', 'ELO Débito'),
( 20034,  'Policard', 'debito', 'FROTA;PAT'),
( 20036,  'Banescard', 'debito', 'BANESE CARD'),
( 20037,  'Hipercard', 'debito', null),
( 20042,  'Sicredi', 'debito', null),
( 20059,  'Banpará', 'debito', null),
( 20071,  'Sorocred', 'debito', null)

merge bandeira as b
using ##bandeira as b2
on b.id = b2.id
when matched then
  update set
  b.nome = b2.nome,
  b.tipo = b2.tipo
when not matched then
  insert
  (id, nome, tipo, aliases)
  values
  (b2.id, b2.nome, b2.tipo, b2.aliases);

go
